### ISSUE TITLE
retroarch wont load properly

### ISSUE THREAD

**Issue by ravenkid** [hpcodecraft/Gameshell#4]
![20190329214327](https://user-images.githubusercontent.com/49037699/55237150-68d13f00-526c-11e9-9e48-0da3a799aa3e.png)
Downloading Retroarch...
Cloning into 'retroarch'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Installing Retroarch...
./retroarch/setup_retroarch.sh: line 21: cd: retroarch: No such file or directory
./retroarch/setup_retroarch.sh: line 22: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Installing video filters...
./retroarch/setup_retroarch.sh: line 26: cd: gfx/video_filters: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat '*.filt': No such file or directory
cp: cannot stat '*.so': No such file or directory
Updating retroarch.cfg...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 97511  100 97511    0     0   7205      0  0:00:13  0:00:13 --:--:--  8112
Cleaning up...

Done! Retroarch is ready to use!

**Comment by jigglycrumb** [comment]
Sorry for the late reply, I didn't notice this issue was opened.

Judging from your logs it seems that the internet connection was interrupted and retroarch didn't download properly. As a result, the following steps of the script expecting the files failed.
Have you tried just running it again?

**Comment by jigglycrumb** [comment]
The setup script has been updated and the problematic config file isn't installed anymore, so this issue should be fixed :)
