### ISSUE TITLE
After script completes, RetroArch opens a TTY console window

### ISSUE THREAD

**Issue by crazyn8** [hpcodecraft/Gameshell#6]
I ran your script and everything went fine - it completed correctly.  Afterwards, however, opening the RetroArch icon on the launcher doesn't invoke RetroArch.  Rather, it takes you to a new Linux console window.  I see:

Debian GNU/Linux 9 clockworkpi tty5

clockworkpi login:

**Comment by shademalek** [comment]
Can confirm. I just ran the script and have the same issue.

**Comment by shademalek** [comment]
Ok, I found that by backing up the Retroarch config and restoring it after this script, Retroarch launches normally again. Something is definitely not getting set correctly by the Retroarch config tool. All other parts of this worked perfectly though!

**Comment by jigglycrumb** [comment]
Installation of the config file has been disabled for now, so I'll close this issue. I'll check the config and maybe make it an optional step in the script. The config is still included in the repo so anyone who wants to use (or debug 😛) it can copy it manually.
