### ISSUE TITLE
Can I use it in deot os GameShell?

### ISSUE THREAD

**Issue by WangTingZheng** [hpcodecraft/Gameshell#7]
I use deot v1 OS on original GameShell and 32GB SD card
After finished runing 
```
bash <(curl -s https://raw.githubusercontent.com/hpcodecraft/gameshell-setup/master/run.sh)
```
It's ok.
but when I run
```
source ~/.bash_aliases
```
showed
```
-bash: /home/cpi/.bash_aliases: No such file or directory
```
and my storage still 16GB, not 32GB

**Comment by WangTingZheng** [comment]
and when I run 
```
bash <(curl -s https://raw.githubusercontent.com/hpcodecraft/gameshell-setup/master/run.sh)
```
I had no printf info, it's seems no ok:(

**Comment by WangTingZheng** [comment]
it' done! It seems to be my network problem.

**Comment by jigglycrumb** [comment]
@WangTingZheng Did it work with DEOT? I've never tried :D

**Comment by WangTingZheng** [comment]
> 
> 
> @WangTingZheng Did it work with DEOT? I've never tried :D

It worked! Perfectly!
